// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'art_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ArtModel _$ArtModelFromJson(Map<String, dynamic> json) => ArtModel(
      objectID: json['objectID'] as int?,
      isHighlight: json['isHighlight'] as bool?,
      accessionNumber: json['accessionNumber'] as String?,
      accessionYear: json['accessionYear'] as String?,
      isPublicDomain: json['isPublicDomain'] as bool,
      primaryImage: json['primaryImage'] as String?,
      primaryImageSmall: json['primaryImageSmall'] as String?,
      additionalImages: (json['additionalImages'] as List<dynamic>)
          .map((e) => e as String?)
          .toList(),
      constituents: (json['constituents'] as List<dynamic>?)
          ?.map((e) => ConstituentsModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      department: json['department'] as String?,
      objectName: json['objectName'] as String?,
      title: json['title'] as String?,
      culture: json['culture'] as String?,
      period: json['period'] as String?,
      dynasty: json['dynasty'] as String?,
      reign: json['reign'] as String?,
      portfolio: json['portfolio'] as String?,
      artistRole: json['artistRole'] as String?,
      artistPrefix: json['artistPrefix'] as String?,
      artistDisplayName: json['artistDisplayName'] as String?,
      artistDisplayBio: json['artistDisplayBio'] as String?,
      artistSuffix: json['artistSuffix'] as String?,
      artistAlphaSort: json['artistAlphaSort'] as String?,
      artistNationality: json['artistNationality'] as String?,
      artistBeginDate: json['artistBeginDate'] as String?,
      artistEndDate: json['artistEndDate'] as String?,
      artistGender: json['artistGender'] as String?,
      artistWikidata_URL: json['artistWikidata_URL'] as String?,
      artisULAN_URL: json['artisULAN_URL'] as String?,
      objectDate: json['objectDate'] as String?,
      obljectBeginDate: json['obljectBeginDate'] as int?,
      ObjectEndDate: json['ObjectEndDate'] as int?,
      medium: json['medium'] as String?,
      dimensions: json['dimensions'] as String?,
      dimensionsParsed: (json['dimensionsParsed'] as num?)?.toDouble(),
      measurments: (json['measurments'] as List<dynamic>?)
          ?.map((e) => MeasurmentsModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      creditLine: json['creditLine'] as String?,
      geographyType: json['geographyType'] as String?,
      city: json['city'] as String?,
      state: json['state'] as String?,
      county: json['county'] as String?,
      country: json['country'] as String?,
      region: json['region'] as String?,
      subregion: json['subregion'] as String?,
      locale: json['locale'] as String?,
      locus: json['locus'] as String?,
      excavation: json['excavation'] as String?,
      river: json['river'] as String?,
      classification: json['classification'] as String?,
      rightsAndReproduction: json['rightsAndReproduction'] as String?,
      linkResource: json['linkResource'] as String?,
      metadataDate: json['metadataDate'] == null
          ? null
          : DateTime.parse(json['metadataDate'] as String),
      repository: json['repository'] as String?,
      ObjectURL: json['ObjectURL'] as String?,
      tags: (json['tags'] as List<dynamic>?)
          ?.map((e) => TagsModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      objectWikidata_URL: json['objectWikidata_URL'] as String?,
      isTimelimeWork: json['isTimelimeWork'] as bool?,
      GalleryNumber: json['GalleryNumber'] as String?,
    );

Map<String, dynamic> _$ArtModelToJson(ArtModel instance) => <String, dynamic>{
      'objectID': instance.objectID,
      'isHighlight': instance.isHighlight,
      'accessionNumber': instance.accessionNumber,
      'accessionYear': instance.accessionYear,
      'isPublicDomain': instance.isPublicDomain,
      'primaryImage': instance.primaryImage,
      'primaryImageSmall': instance.primaryImageSmall,
      'additionalImages': instance.additionalImages,
      'constituents': instance.constituents,
      'department': instance.department,
      'objectName': instance.objectName,
      'title': instance.title,
      'culture': instance.culture,
      'period': instance.period,
      'dynasty': instance.dynasty,
      'reign': instance.reign,
      'portfolio': instance.portfolio,
      'artistRole': instance.artistRole,
      'artistPrefix': instance.artistPrefix,
      'artistDisplayName': instance.artistDisplayName,
      'artistDisplayBio': instance.artistDisplayBio,
      'artistSuffix': instance.artistSuffix,
      'artistAlphaSort': instance.artistAlphaSort,
      'artistNationality': instance.artistNationality,
      'artistBeginDate': instance.artistBeginDate,
      'artistEndDate': instance.artistEndDate,
      'artistGender': instance.artistGender,
      'artistWikidata_URL': instance.artistWikidata_URL,
      'artisULAN_URL': instance.artisULAN_URL,
      'objectDate': instance.objectDate,
      'obljectBeginDate': instance.obljectBeginDate,
      'ObjectEndDate': instance.ObjectEndDate,
      'medium': instance.medium,
      'dimensions': instance.dimensions,
      'dimensionsParsed': instance.dimensionsParsed,
      'measurments': instance.measurments,
      'creditLine': instance.creditLine,
      'geographyType': instance.geographyType,
      'city': instance.city,
      'state': instance.state,
      'county': instance.county,
      'country': instance.country,
      'region': instance.region,
      'subregion': instance.subregion,
      'locale': instance.locale,
      'locus': instance.locus,
      'excavation': instance.excavation,
      'river': instance.river,
      'classification': instance.classification,
      'rightsAndReproduction': instance.rightsAndReproduction,
      'linkResource': instance.linkResource,
      'metadataDate': instance.metadataDate?.toIso8601String(),
      'repository': instance.repository,
      'ObjectURL': instance.ObjectURL,
      'tags': instance.tags,
      'objectWikidata_URL': instance.objectWikidata_URL,
      'isTimelimeWork': instance.isTimelimeWork,
      'GalleryNumber': instance.GalleryNumber,
    };
